In [ ]:
a="HELLO WORLD"
a[-5:]

'WORLD'

In [ ]:
a=True
type(a)

In [ ]:
expr = 10 + 20 * 30 * (8/4) / 2
print(expr)

In [ ]:
print("hi this is python")

hi this is python


In [ ]:
list1=[1,2]
list1

[1, 2]

In [ ]:
a=4
print(a)

4


In [ ]:
a=6+7j
type(a)

complex

In [ ]:
x=45
y=2
#a=x+y
print(x%y)

1


In [ ]:
a="python"
len(a)
a[-5:]
a[5]


'n'

In [ ]:
x=1
y=2
result = x<=y
print(result)

True


In [ ]:
X = 3
result = (X < 1) or (X < 10)
print(result)


True


In [ ]:
a="lion"
len(a)

4

In [ ]:
expr = 10 + 20 * 30 * (8/4) / 2
print(expr)

610.0


In [ ]:
animals = ['cat', 'dog', 'rabbit', 'horse']

index = animals.index('dog')

print(index)

1


In [ ]:
a="python"
a.find("t")

2

In [ ]:
a="hello"
a.find("e")

1

In [ ]:
list=["a","b",6,7,8.9,7]
list

['a', 'b', 6, 7, 8.9, 7]

In [ ]:
list1=["a",1,4,9.8]
list1

In [ ]:
fruits = ["Apple", "Banana", "Papaya", "Grapes", "Watermelon"]
print(fruits)

['Apple', 'Banana', 'Papaya', 'Grapes', 'Watermelon']


In [ ]:
fruits = ["Apple", "Banana", "Papaya", "Grapes", "Watermelon"]
num = len(fruits)
print(fruits)
print(len(fruits))

['Apple', 'Banana', 'Papaya', 'Grapes', 'Watermelon']
5


In [ ]:
list=[3,7,8,9]
len(list)

4

In [ ]:
odd_numbers = [1, 3, 5, 7, 9]
print(odd_numbers)

[1, 3, 5, 7, 9]


In [ ]:
odd=[1,3,5,5,5]
odd

[1, 3, 5, 5, 5]

In [ ]:
odd_numbers = [1, 3, 5, 7, 9]
#last_three_odd = odd_numbers[-3:]
#print("Last 3 odd numbers:", last_three_odd)
odd_numbers[-2:]

[7, 9]

In [ ]:
odd_numbers = [1, 3, 5, 7, 9]
even_numbers = [2, 4, 6, 8]

odd_numbers.extend(even_numbers)
print("Updated list:", odd_numbers)


Updated list: [1, 3, 5, 7, 9, 2, 4, 6, 8]


In [ ]:
odd=[1,3,5]
even=[2,4,6]
even.extend(odd)
even

[2, 4, 6, 1, 3, 5]

In [ ]:
fruits = ["apple", "banana", "apple", "orange"]
print(fruits)


In [ ]:
vegetables = ["Tomato", "Carrot", "Potato", "Ginger", "Lemon"]
print(vegetables)


['Tomato', 'Carrot', 'Potato', 'Ginger', 'Lemon']


In [ ]:
list=[1,2,3]
list.remove(2)
list

[1, 3]

In [ ]:
vegetables = ["Tomato", "Carrot", "Potato", "Ginger", "Lemon"]
vegetables.remove("Ginger")
vegetables
#print("Updated list:", vegetables)


['Tomato', 'Carrot', 'Potato', 'Lemon']

In [ ]:
vegetables = ["Tomato", "Carrot", "Potato", "Ginger", "Lemon"]
#index = vegetables.index("Ginger")
vegetables.insert(3, "Chilli")
vegetables
vegetables.remove("Ginger")
print("Updated list:", vegetables)


Updated list: ['Tomato', 'Carrot', 'Potato', 'Chilli', 'Lemon']


In [ ]:
list=[1,2,3]
list.insert(1,4)
list

[1, 4, 2, 3]

In [ ]:
vegetables = ["Tomato", "Carrot", "Potato", "Chilli", "Lemon", "Avocado", "Artichoke"]
selected_vegetables = [vegetable for vegetable in vegetables if vegetable.endswith("o")]
print("Selected vegetables:", selected_vegetables)


Selected vegetables: ['Tomato', 'Potato', 'Avocado']


In [ ]:
fruits = ("Apple", "Banana", "Papaya", "Grapes", "Watermelon")
print(fruits)


('Apple', 'Banana', 'Papaya', 'Grapes', 'Watermelon')


In [ ]:
nums=(1,2,3,4,5)
nums

(1, 2, 3, 4, 5)

In [ ]:

fruits = ("Apple", "Banana", "Papaya", "Grapes", "Watermelon")
num_items = len(fruits)
print("Number of items in the tuple:", num_items)


In [ ]:
nums=(2,5,6)
number=len(nums)
number

3

In [ ]:
odd_numbers = (1, 3, 5, 7, 9)
print(odd_numbers)


(1, 3, 5, 7, 9)


In [ ]:
odd_numbers = (1, 3, 5, 7, 9)
last_three_odd = odd_numbers[-1:]
print("Last 3 odd numbers:", last_three_odd)


Last 3 odd numbers: (9,)


In [ ]:
odd_numbers = (1, 3, 5, 7, 9)
even_numbers = (2, 4, 6, 8, 10, 12, 14, 16)

all_numbers = odd_numbers + even_numbers
print("Combined tuple:", all_numbers)


Combined tuple: (1, 3, 5, 7, 9, 2, 4, 6, 8, 10, 12, 14, 16)


In [ ]:
odd=(1,3)
even=(2,4)
all=even+odd
all

(2, 4, 1, 3)

In [ ]:
my_tuple = (1, 2, 3, 2, 4, 5, 4,4,4,4)
print(my_tuple)


(1, 2, 3, 2, 4, 5, 4, 4, 4, 4)


In [ ]:
vegetables = ("Tomato", "Carrot", "Potato", "Ginger", "Lemon")
print(vegetables)


('Tomato', 'Carrot', 'Potato', 'Ginger', 'Lemon')


In [ ]:
vegetables = ("Tomato", "Carrot", "Potato", "Ginger", "Lemon")
updated_vegetables = tuple("Onion" if veg == "Beans" else veg for veg in vegetables)
print("Updated tuple:", updated_vegetables)


Updated tuple: ('Tomato', 'Carrot', 'Potato', 'Ginger', 'Lemon')


In [ ]:
int=(1,2,3)
str=("a","b")
update=tuple(4 if i==3 else i for i in int)
update

(1, 2, 4)

In [ ]:
fruits = ("Apple", "Banana", "Papaya", "Grapes", "Watermelon")
# Packing
packed_fruits = fruits
print("Packed tuple:", packed_fruits)

# Unpacking
f1, fruit2, fruit3, fruit4, fruit5 = fruits
print("Unpacked values:")
print("Fruit 1:", f1)
print("Fruit 2:", fruit2)
print("Fruit 3:", fruit3)
print("Fruit 4:", fruit4)
print("Fruit 5:", fruit5)


Packed tuple: ('Apple', 'Banana', 'Papaya', 'Grapes', 'Watermelon')
Unpacked values:
Fruit 1: Apple
Fruit 2: Banana
Fruit 3: Papaya
Fruit 4: Grapes
Fruit 5: Watermelon


In [ ]:
car_details = {
    "Brand": "Ford",
    "Model": "Mustang",
    "Manufactured year": 1964
}
print(car_details)


{'Brand': 'Ford', 'Model': 'Mustang', 'Manufactured year': 1964}


In [ ]:
nums={
    "brand":"four",
    "color":"red"
}
#nums["num"]="eight"
del nums["color"]
nums


{'brand': 'four'}

In [ ]:
car_details = {
    "Brand": "Ford",
    "Model": "Mustang",
    "Manufactured year": 1964
}

br = car_details["Brand"]
print("Brand value:", br)


Brand value: Ford


In [ ]:
car_details = {
    "Brand": "Ford",
    "Model": "Mustang",
    "Manufactured year": 1964
}

car_details["Color"] = "Red"
print("Updated car details:", car_details)


Updated car details: {'Brand': 'Ford', 'Model': 'Mustang', 'Manufactured year': 1964, 'Color': 'Red'}


In [ ]:
car_details = {
    "Brand": "Ford",
    "Model": "Mustang",
    "Manufactured year": 1964,
    "Color": "Red"
}

del car_details["Model"]
print("Updated car details:", car_details)


In [ ]:
car_details = {
    "Brand": "Ford",
    "Model": "Mustang",
    "Manufactured year": 1964,
    "Color": "Red"
}

car_details["Brand"] = 'benz'
print("Updated car details:", car_details)


Updated car details: {'Brand': 'benz', 'Model': 'Mustang', 'Manufactured year': 1964, 'Color': 'Red'}


In [ ]:
devices = {"TV", "Mobile", "Speaker", "Bluetooth", "Laptop"}
print(devices)


{'Mobile', 'Bluetooth', 'Laptop', 'Speaker', 'TV'}


In [ ]:
nums={1,2,3,4,4,5,5,5,5,55,5,7}
nums

{1, 2, 3, 4, 5, 7, 55}

In [ ]:
devices = {"TV", "Mobile", "Speaker", "Bluetooth", "Laptop"}

for device in devices:
    print(device)


Mobile
Bluetooth
Laptop
Speaker
TV


In [ ]:
my_set = {1, 2, 3, 2, 4, 5, 4}
print(my_set)


{1, 2, 3, 4, 5}


In [ ]:
devices = {"TV", "Mobile", "Speaker", "Bluetooth", "Laptop"}
devices.add("Charger")
print(devices)


{'Mobile', 'Bluetooth', 'Laptop', 'Speaker', 'Charger', 'TV'}


In [ ]:
devices = {'Speaker', 'Laptop', 'TV', 'Mobile', 'Charger', 'Bluetooth'}
devices.remove("Bluetooth")
print(devices)


{'Mobile', 'Laptop', 'Speaker', 'Charger', 'TV'}


In [ ]:
sets={1,2,3}
sets.add(6)
sets.remove(2)
sets

{1, 3, 6}

In [ ]:
sets={1,2,3}
sets.remove(2)
sets

{1, 3}

In [ ]:
a=24
a!=32

True

In [ ]:
a=24
a==32

False

In [ ]:
a=7
a>9

False

In [ ]:
i=9
i==5

False

In [ ]:
a=24
a<32

True

In [ ]:
a=24
a>32

False

In [ ]:
a=24
a>=32

False

In [ ]:
a=24
a<=32

True

In [ ]:
a = 10
b = 20
if a<b:
  print("a is lesser")

a is lesser


In [ ]:
a = 30
b = 3
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")
elif b<a:
  print("b is lesser")

b is lesser


In [ ]:
a = 200
b = 33
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")
else:
  print("a is greater than b")

a is greater than b


In [ ]:
a=2
b=8
if a>b:
   print("a greater")
else:
  print("a lesser")

a lesser


In [ ]:
List = ["Diary”, “Record”, “Notes”, “Manual”, “Text book”, “Xerox", "Book", "Laptop"]
for x in List:
  print(x)

Diary”, “Record”, “Notes”, “Manual”, “Text book”, “Xerox
Book
Laptop


In [ ]:
colors=["red","white","pink"]
for x in colors:
  print(x)

red
white
pink


In [ ]:
List = ["Diary”, “Record”, “Notes”, “Manual”, “Text book”, “Xerox"]
for x in List:
  print(x)

Diary”, “Record”, “Notes”, “Manual”, “Text book”, “Xerox


In [ ]:
items = ["Diary", "Record", "Notes", "Manual", "Text book", "Xerox"]

for item in items:
    print(item)
    if item == "Notes":
        break

Diary
Record
Notes


In [ ]:
list=[1,2,3]
for x in list:
  print(x)
  if x==2:
    break



1
2


In [ ]:
list=[1,2,3,5,8]
for i in list:
  #print(i)
  if i==2:
    break
    print(i)
    #print(i)


In [ ]:
items = ["Diary", "Record", "Notes", "Manual", "Text book", "Xerox"]

for item in items:
    if item == "Xerox":
        continue
    print(item)

Diary
Record
Notes
Manual
Text book


In [ ]:
for x in range (2, 30, 3):
  print(x)


2
5
8
11
14
17
20
23
26
29


In [ ]:
for x in range(100,1,-7):
  print(x)

100
93
86
79
72
65
58
51
44
37
30
23
16
9
2


In [ ]:
for x in range (7):
  print(x)
else:
   print("finish")

0
1
2
3
4
5
6
finish


In [ ]:

adj = ["big","amazing","small","blue"]
List = ["Diary”, “Record”, “Notes”, “Manual”, “Text book”, “Xerox"]
for x in adj:
  for y in List:
    print(x, y)

big Diary”, “Record”, “Notes”, “Manual”, “Text book”, “Xerox
amazing Diary”, “Record”, “Notes”, “Manual”, “Text book”, “Xerox
small Diary”, “Record”, “Notes”, “Manual”, “Text book”, “Xerox
blue Diary”, “Record”, “Notes”, “Manual”, “Text book”, “Xerox


In [ ]:
a=[1,2,3]
b=[4,5,6]
for x in a:
  for y in b:
    print(x,y)

1 4
1 5
1 6
2 4
2 5
2 6
3 4
3 5
3 6


In [ ]:
num = 0
while num == 15:
    print(num)
    num += 1#num=num+1

In [ ]:
num = 0
while num < 6:
    print(num)
    if num == 3:
        break
    num=num+1

0
1
2
3


In [ ]:
num = 0
while num < 6:
    if num == 3:
        num += 1
        continue
    print(num)
    num += 1

0
1
2
4
5


In [ ]:
for num in range(4):
    print(num)
else:
    print("Loop completed")

0
1
2
3
Loop completed


In [ ]:
x = -1

if x < 0:
  raise Exception("Sorry, no numbers below zero")

Exception: ignored

In [ ]:
def All_is_well():
    print("Everything is well!")

# Call the function
All_is_well()

Everything is well!


In [ ]:
def function():
  print("hi")
function()

hi


In [ ]:
n = 100
fact = 1
for i in range(1, n+1):
    fact = fact * i
#print("The factorial of 100 is : ", end="")
print(fact)

93326215443944152681699238856266700490715968264381621468592963895217599993229915608941463976156518286253697920827223758251185210916864000000000000000000000000


In [ ]:
def my_function(fname):
  print(fname+ "Thomas")

my_function("Edison")
my_function("Dewey")

EdisonThomas
DeweyThomas


In [ ]:
def find_square(integer1=5625):
    result = integer1 * integer1
    return result
result = find_square()
print(result)

31640625


In [ ]:
def squ(int=8):
  res=int*int
  return res
res=squ()
print(res)

64


In [ ]:
def find_sq(int1=45):
  result=int1*int1
  return result
result=find_sq()
print(result)


2025


In [ ]:
def add(*num):
    sum = 0;
    for n in num:
        sum = sum + n;
    print("Sum:", sum)


add(1,2,3,5,6,7,8,9,3,5)
add(1,2,3)
add(2,4)

Sum: 49
Sum: 6
Sum: 6


In [ ]:
def myfun(Candidate1, Candidate2, Candidate3):
  print("The PM of India is " + Candidate1)

myfun(Candidate1 = "Narendra Modi",
      Candidate2 = "Droupadi Murmu",
      Candidate3 = "Gandhi")

The PM of India is Narendra Modi


In [ ]:
def isPalindrome(s):
    return s == s[::-1]


# Driver code
s = "malayalam"
ans = isPalindrome(s)

if ans:
    print("Yes")
else:
    print("No")

Yes


In [ ]:
setA = {10, 20, 30, 40, 80}
setB = {10, 20, 80, 40, 50}
difference = setA - setB
print(difference)
#items present only in the first set and not in second set are returned

{30}


In [ ]:
setA={1,2,3}
setB={4,5,3}
difference=setB-setA
print(difference)

{4, 5}


In [ ]:
setA = {10, 20, 30, 40, 80}
setB = {100, 30, 80, 40, 60}
setB.add(9)
print(setB)

{80, 100, 40, 9, 60, 30}


In [ ]:
set1={1,2,3}
set2={9,7,6}
set1.add(5)
print(set1)

{1, 2, 3, 5}


In [ ]:
setA = {10, 20, 30, 40, 80}
setB = {100, 30, 80, 40, 60}
setA.clear()
print(setA)

set()


In [ ]:
my_list = [10, 2, 8, 7, 5, 4, 3, 11, 0, 1]
result = list(filter(lambda x: x > 6, my_list))
print(result)


[10, 8, 7, 11]


In [ ]:
my_list = [10, 2, 8, 7, 5, 4, 3, 11, 0, 1]
result = list(filter(lambda x:x%2!=0, my_list))
print(result)

[7, 5, 3, 11, 1]


In [ ]:
import numpy
arr = numpy.array([1, 3, 5, 7, 9])
print(arr)

[1 3 5 7 9]


In [ ]:
arr = numpy.array([1, 3, 5, 7, 9])
print(arr)
print(type(arr))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [ ]:
a=numpy.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
import numpy as np
arr = np.array(42)
print(arr)

42


In [ ]:
import numpy as np
arr=np.array(9)
print(arr)

9


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5,8,9,6,77,88,99])
print(arr)

[ 1  2  3  4  5  8  9  6 77 88 99]


In [ ]:
import numpy as np
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6],[2,4,6]])
print(arr)

[[1 2 3]
 [4 5 6]
 [2 4 6]]


In [ ]:
#import numpy as np
a=np.array([[1,2],[2,3]])
print(a)

[[1 2]
 [2 3]]


In [ ]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]],
                [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
import numpy as np
arr=np.array([[[1,2],[3,4]],
              [[5,6],[7,8]],
              [[3,4],[6,7]]])
print(arr[1,0,0])
print(arr.ndim)

5
3


In [ ]:
import numpy as np
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]],
              [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:

import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0,4,5])


2nd element on 1st row:  5


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr.shape)

(7,)


In [ ]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4,7,9,4], ndmin=6)

print(arr)
print('shape of array :', arr.shape)


[[[[[[1 2 3 4 7 9 4]]]]]]
shape of array : (1, 1, 1, 1, 1, 7)


In [ ]:
arr = np.array([9, 8, 2, 7, 6, 5, 4, 3, 1])
arr[::1]. sort ()
print(arr)

[1 2 3 4 5 6 7 8 9]


In [ ]:
arr = np.array([9, 8, 2, 7, 6, 5, 4, 3, 1])
arr[::-1]. sort ()
print(arr)

[9 8 7 6 5 4 3 2 1]


In [ ]:
arr = np.array([9, 8, 2, 7, 6, 5, 4, 3, 1])
arr. sort ()
print(arr)

[1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[::1].sort()
print(arr)

[1 2 3 4 5 6 7]


In [ ]:
import pandas as pd
#pip install pandas
a = [1, 7, 2]
myvar = pd.Series(a)
print(myvar)

0    1
1    7
2    2
dtype: int64


In [ ]:
import pandas as pd
a=[1,2,3,5,6,7]
var=pd.Series(a,index=["a","b","c","d","e","f"])
print(var)

a    1
b    2
c    3
d    5
e    6
f    7
dtype: int64


In [ ]:
a = [1, 7, 2]
myvar = pd.Series(a, index = ["x", "y", "z"])
print(myvar)

x    1
y    7
z    2
dtype: int64


In [ ]:
calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories)

print(myvar)


day1    420
day2    380
day3    390
dtype: int64


In [ ]:
cal = {"day1": 420, "day2": 38}

a = pd.Series(cal)

print(a)

day1    420
day2     38
dtype: int64


In [ ]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

d = pd.DataFrame(data)

print(d)


   calories  duration
0       420        50
1       380        40
2       390        45


In [ ]:
cal = {
  "calories": [420, 380, 390],
  "duration": [50, 40,56]
}

dfm = pd.DataFrame(cal)

print(dfm)

   calories  duration
0       420        50
1       380        40
2       390        56


In [ ]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data)

print(df.loc[2])


calories    390
duration     45
Name: 2, dtype: int64


In [ ]:
data = {
  "calories": [420, 380, 390,6778,78],
  "duration": [50, 40, 45,900,78]
}

df = pd.DataFrame(data)

print(df.loc[3])


calories    6778
duration     900
Name: 3, dtype: int64
